import crypto from 'node:crypto'
import express, { type NextFunction, type Request, type Response } from 'express'
import cors from 'cors'
import multer from 'multer'
import { config, hasGemini, hasSupabase } from './config.js'
import { analyzeWithGemini, checkGeminiConnectivity } from './gemini.js'
import { finalizeRisk } from './riskEngine.js'
import { getAdmin, requireUser } from './supabase.js'
import type { InputType } from '../src/types/risk.js'

const app = express()
app.set('trust proxy', 1)
const allowedImageTypes = new Set(['image/png', 'image/jpeg', 'image/webp'])
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: config.maxUploadBytes, files: 1 }, fileFilter: (_req, file, cb) => cb(null, allowedImageTypes.has(file.mimetype) && /\.(png|jpe?g|webp)$/i.test(file.originalname)) })
const requestCounts = new Map<string, { started: number; count: number }>()
const rateLimit = (req: Request, res: Response, next: NextFunction) => { const key = req.ip || 'unknown'; const current = requestCounts.get(key); const now = Date.now(); if (!current || now - current.started > 60_000) requestCounts.set(key, { started: now, count: 1 }); else if (++current.count > 20) return res.status(429).json({ error: 'Please wait a moment before running another analysis.' }); next() }
const allowedOrigins = new Set([config.appOrigin, 'http://localhost:5175', 'http://127.0.0.1:5175'].filter(Boolean))
app.use(cors({ credentials: true, origin: (origin, callback) => { if (!origin || allowedOrigins.has(origin) || origin.startsWith('chrome-extension://')) return callback(null, true); return callback(new Error('Origin is not allowed.')) } }))
app.use(express.json({ limit: '1mb' }))

const log = (req: Request, status: number, started: number, extra: Record<string, unknown> = {}) => console.info(JSON.stringify({ requestId: req.headers['x-request-id'] || crypto.randomUUID(), path: req.path, status, durationMs: Date.now() - started, ...extra }))
const asyncRoute = (handler: (req: Request, res: Response) => Promise<unknown>) => (req: Request, res: Response, next: NextFunction) => handler(req, res).catch(next)

async function runAnalysis(content: string, inputType: InputType, image?: { mimeType: string; data: string }) {
  if (!hasGemini) throw Object.assign(new Error('Gemini AI is not configured.'), { status: 503 })
  try { return { id: crypto.randomUUID(), createdAt: new Date().toISOString(), inputType, content, ...finalizeRisk(await analyzeWithGemini(content, inputType, image), content), mode: 'live' as const } }
  catch (error) {
    console.warn(JSON.stringify({ event: 'gemini_unavailable', message: error instanceof Error ? error.message : 'unknown error' }))
    throw Object.assign(new Error('Gemini AI is temporarily unavailable. No analysis was generated.'), { status: 503 })
  }
}

const hashShareToken = (token: string) => crypto.createHash('sha256').update(token).digest('hex')
const createShareToken = () => crypto.randomBytes(32).toString('base64url')
const publicOrigin = () => config.appOrigin || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://127.0.0.1:5175')

async function createScopedShare(client: ReturnType<typeof getAdmin>, userId: string, incidentId: string) {
  const token = createShareToken()
  const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString()
  const { error } = await client!.from('shared_incident_links').insert({ incident_id: incidentId, user_id: userId, token_hash: hashShareToken(token), expires_at: expiresAt })
  if (error) throw error
  return { url: `${publicOrigin()}/shared/${token}`, expiresAt }
}

async function queueTrustedNotifications(client: ReturnType<typeof getAdmin>, userId: string, incident: { id: string; severity: string; summary: string }, contactId?: string) {
  if (!contactId && !['HIGH', 'CRITICAL'].includes(incident.severity)) return []
  let contactsQuery = client!.from('trusted_contacts').select('id,name,email').eq('user_id', userId).eq('enabled', true).eq('consent_granted', true)
  if (contactId) contactsQuery = contactsQuery.eq('id', contactId)
  const { data: contacts, error } = await contactsQuery
  if (error) throw error
  const notifications: Array<{ contact: string; status: string; shareUrl: string; expiresAt: string }> = []
  for (const contact of contacts || []) {
    const share = await createScopedShare(client, userId, incident.id)
    let status = 'Notification queued — delivery not yet configured'
    if (config.resendApiKey) {
      const response = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { authorization: `Bearer ${config.resendApiKey}`, 'content-type': 'application/json' }, body: JSON.stringify({ from: config.notificationFrom, to: [contact.email], subject: 'A Sentinel incident was shared with you', html: `<p>A Sentinel user chose to share one incident with you.</p><p><a href="${share.url}">Open the private incident view</a></p><p>This link expires in 7 days and shows only that incident.</p>` }) })
      status = response.ok ? 'Notification sent' : 'Notification queued — email delivery failed'
    }
    await client!.from('incident_events').insert({ incident_id: incident.id, user_id: userId, event_type: 'trusted_notification_queued', metadata: { contact_id: contact.id, status, expires_at: share.expiresAt } })
    notifications.push({ contact: contact.name, status, shareUrl: share.url, expiresAt: share.expiresAt })
  }
  return notifications
}

function validateImageBuffer(file: Express.Multer.File) {
  const bytes = file.buffer
  const isPng = bytes.length >= 8 && bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))
  const isJpeg = bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff
  const isWebp = bytes.length >= 12 && bytes.subarray(0, 4).toString('ascii') === 'RIFF' && bytes.subarray(8, 12).toString('ascii') === 'WEBP'
  if (!allowedImageTypes.has(file.mimetype) || !(isPng || isJpeg || isWebp)) throw Object.assign(new Error('The uploaded file is not a supported image.'), { status: 400 })
}

app.get('/api/health', asyncRoute(async (_req, res) => { let database: 'ready' | 'not_configured' | 'unavailable' = 'not_configured'; let storage: 'ready' | 'not_configured' | 'unavailable' = 'not_configured'; if (hasSupabase) { const client = getAdmin()!; const dbCheck = await client.from('incidents').select('id', { head: true, count: 'exact' }); database = dbCheck.error ? 'unavailable' : 'ready'; const storageCheck = await client.storage.getBucket('sentinel-evidence'); storage = storageCheck.error ? 'unavailable' : 'ready' } const ai: 'ready' | 'not_configured' | 'unavailable' = !hasGemini ? 'not_configured' : await checkGeminiConnectivity() ? 'ready' : 'unavailable'; const operational = ai !== 'unavailable' && (!hasSupabase || (database === 'ready' && storage === 'ready')); res.status(operational ? 200 : 503).json({ status: operational ? 'ok' : 'degraded', services: { database, storage, ai } }) }))
app.post('/api/analyze/text', rateLimit, asyncRoute(async (req, res) => { const started = Date.now(); const content = typeof req.body?.content === 'string' ? req.body.content.trim() : ''; if (!content) return res.status(400).json({ error: 'Content is required.' }); if (content.length > 12000) return res.status(413).json({ error: 'Please keep the content under 12,000 characters.' }); const result = await runAnalysis(content, 'message'); log(req, 200, started, { provider: result.provider }); res.json(result) }))
app.post('/api/analyze/url', rateLimit, asyncRoute(async (req, res) => { const started = Date.now(); const content = typeof req.body?.url === 'string' ? req.body.url.trim() : ''; if (content.length > 2048) return res.status(413).json({ error: 'Please keep the URL under 2,048 characters.' }); try { const parsed = new URL(content); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error() } catch { return res.status(400).json({ error: 'Enter a valid HTTP or HTTPS URL.' }) } const result = await runAnalysis(content, 'website'); log(req, 200, started, { provider: result.provider }); res.json(result) }))
app.post('/api/analyze/image', rateLimit, upload.single('image'), asyncRoute(async (req, res) => { const started = Date.now(); if (!req.file) return res.status(400).json({ error: 'A PNG, JPEG, or WebP image is required.' }); validateImageBuffer(req.file); const result = await runAnalysis('Uploaded screenshot for visual safety review.', 'screenshot', { mimeType: req.file.mimetype, data: req.file.buffer.toString('base64') }); log(req, 200, started, { provider: result.provider }); res.json(result) }))

app.get('/api/incidents', asyncRoute(async (req, res) => { const user = await requireUser(req); const client = getAdmin()!; const { data, error } = await client.from('incidents').select('*,analysis_results(*),evidence(*)').eq('user_id', user.id).order('created_at', { ascending: false }); if (error) throw error; res.json(data || []) }))
app.get('/api/account/export', asyncRoute(async (req, res) => { const user = await requireUser(req); const client = getAdmin()!; const [profile, incidents, contacts] = await Promise.all([client.from('profiles').select('*').eq('id', user.id).maybeSingle(), client.from('incidents').select('*,analysis_results(*),evidence(*),incident_events(*)').eq('user_id', user.id).order('created_at', { ascending: false }), client.from('trusted_contacts').select('id,name,email,enabled,consent_granted,created_at').eq('user_id', user.id)]); if (profile.error || incidents.error || contacts.error) throw profile.error || incidents.error || contacts.error; res.json({ exportedAt: new Date().toISOString(), account: { id: user.id, email: user.email || null, profile: profile.data }, incidents: incidents.data || [], trustedContacts: contacts.data || [] }) }))
app.delete('/api/incidents', asyncRoute(async (req, res) => { const user = await requireUser(req); const client = getAdmin()!; const { data: evidence } = await client.from('evidence').select('storage_path').eq('user_id', user.id); const paths = (evidence || []).map(item => item.storage_path); if (paths.length) await client.storage.from('sentinel-evidence').remove(paths); const { error } = await client.from('incidents').delete().eq('user_id', user.id); if (error) throw error; res.json({ ok: true, deleted: true }) }))
app.get('/api/incidents/:id', asyncRoute(async (req, res) => { const user = await requireUser(req); const client = getAdmin()!; const { data, error } = await client.from('incidents').select('*,analysis_results(*),evidence(*),incident_events(*)').eq('id', req.params.id).eq('user_id', user.id).single(); if (error || !data) return res.status(404).json({ error: 'Incident not found.' }); const evidence = (data.evidence || [])[0]; let signedUrl: string | undefined; if (evidence?.storage_path) { const signed = await client.storage.from('sentinel-evidence').createSignedUrl(evidence.storage_path, 300); signedUrl = signed.data?.signedUrl } res.json({ ...data, evidence: evidence ? { ...evidence, signed_url: signedUrl } : null }) }))
app.post('/api/incidents', asyncRoute(async (req, res) => { const user = await requireUser(req); const client = getAdmin()!; const body = req.body; const analysis = body.analysis; if (!analysis || typeof analysis.riskScore !== 'number' || !analysis.category || !analysis.severity) return res.status(400).json({ error: 'A structured analysis is required.' }); const { data: incident, error } = await client.from('incidents').insert({ user_id: user.id, source_type: analysis.inputType, category: analysis.category, severity: analysis.severity, risk_score: analysis.riskScore, summary: analysis.summary, explanation: analysis.explanation, status: 'OPEN', ai_provider: analysis.provider || 'gemini', analysis_version: analysis.analysisVersion || '1.0', metadata: { mode: analysis.mode || 'live', originalContent: typeof analysis.content === 'string' ? analysis.content.slice(0, 12000) : '' } }).select().single(); if (error || !incident) throw error || new Error('Incident could not be created.')
  const { error: resultError } = await client.from('analysis_results').insert({ incident_id: incident.id, category: analysis.category, severity: analysis.severity, risk_score: analysis.riskScore, risk_dna: analysis.riskDNA, detected_signals: analysis.detectedSignals, explanation: analysis.explanation, possible_consequences: analysis.consequences || analysis.possibleConsequences, recommended_actions: analysis.recommendedActions, confidence: analysis.confidence, model_name: analysis.modelName || 'gemini', analysis_version: analysis.analysisVersion || '1.0' }); if (resultError) throw resultError
  await client.from('incident_events').insert([{ incident_id: incident.id, user_id: user.id, event_type: 'incident_created', metadata: {} }, { incident_id: incident.id, user_id: user.id, event_type: 'analysis_completed', metadata: { provider: analysis.provider || 'gemini' } }])
  res.status(201).json({ incidentId: incident.id, status: 'OPEN' })
}))
app.post('/api/incidents/:id/evidence', upload.single('evidence'), asyncRoute(async (req, res) => { const user = await requireUser(req); const client = getAdmin()!; if (!req.file) return res.status(400).json({ error: 'Evidence file is required.' }); validateImageBuffer(req.file); const { data: incident } = await client.from('incidents').select('id').eq('id', req.params.id).eq('user_id', user.id).single(); if (!incident) return res.status(404).json({ error: 'Incident not found.' }); const evidenceId = crypto.randomUUID(); const safeName = (req.file.originalname || 'evidence').replace(/[^a-zA-Z0-9._-]/g, '_').slice(-120); const storagePath = `user/${user.id}/incident/${incident.id}/${evidenceId}-${safeName}`; const hash = crypto.createHash('sha256').update(req.file.buffer).digest('hex'); const uploaded = await client.storage.from('sentinel-evidence').upload(storagePath, req.file.buffer, { contentType: req.file.mimetype, upsert: false }); if (uploaded.error) throw uploaded.error; const { data: row, error } = await client.from('evidence').insert({ id: evidenceId, incident_id: incident.id, user_id: user.id, storage_path: storagePath, original_filename: req.file.originalname, mime_type: req.file.mimetype, file_size: req.file.size, sha256_hash: hash, captured_at: req.body.captured_at || null, evidence_type: 'screenshot', description: 'Original screenshot preserved by the user.' }).select().single(); if (error) { await client.storage.from('sentinel-evidence').remove([storagePath]); throw error } await client.from('incident_events').insert({ incident_id: incident.id, user_id: user.id, event_type: 'evidence_saved', metadata: { evidence_id: evidenceId } }); res.status(201).json({ evidence: row, message: 'Evidence preserved securely.' }) }))
app.delete('/api/evidence/:id', asyncRoute(async (req, res) => { const user = await requireUser(req); const client = getAdmin()!; const { data: evidence } = await client.from('evidence').select('*').eq('id', req.params.id).eq('user_id', user.id).single(); if (!evidence) return res.status(404).json({ error: 'Evidence not found.' }); await client.storage.from('sentinel-evidence').remove([evidence.storage_path]); const { error } = await client.from('evidence').delete().eq('id', evidence.id).eq('user_id', user.id); if (error) throw error; await client.from('incident_events').insert({ incident_id: evidence.incident_id, user_id: user.id, event_type: 'evidence_deleted', metadata: { evidence_id: evidence.id } }); res.json({ ok: true }) }))
app.post('/api/reports', asyncRoute(async (req, res) => { const user = await requireUser(req); const client = getAdmin()!; const { incidentId, category, description } = req.body || {}; if (typeof incidentId !== 'string' || typeof description !== 'string' || !description.trim()) return res.status(400).json({ error: 'Incident and description are required.' }); if (description.length > 5000) return res.status(413).json({ error: 'Please keep the report under 5,000 characters.' }); const { data: incident } = await client.from('incidents').select('id').eq('id', incidentId).eq('user_id', user.id).single(); if (!incident) return res.status(404).json({ error: 'Incident not found.' }); const { data: report, error } = await client.from('reports').insert({ incident_id: incidentId, user_id: user.id, category: typeof category === 'string' && category.trim() ? category.trim().slice(0, 120) : 'Safety concern', description: description.trim(), status: 'SUBMITTED' }).select().single(); if (error) throw error; await client.from('incident_events').insert({ incident_id: incidentId, user_id: user.id, event_type: 'report_created', metadata: { report_id: report.id } }); res.status(201).json(report) }))

app.get('/api/trusted-contacts', asyncRoute(async (req, res) => { const user = await requireUser(req); const { data, error } = await getAdmin()!.from('trusted_contacts').select('id,name,email,enabled,consent_granted,created_at').eq('user_id', user.id).order('created_at', { ascending: false }); if (error) throw error; res.json(data || []) }))
app.post('/api/trusted-contacts', asyncRoute(async (req, res) => { const user = await requireUser(req); const name = typeof req.body?.name === 'string' ? req.body.name.trim() : ''; const email = typeof req.body?.email === 'string' ? req.body.email.trim().toLowerCase() : ''; const consentGranted = req.body?.consentGranted === true; if (!name || !/^\S+@\S+\.\S+$/.test(email)) return res.status(400).json({ error: 'Enter a name and valid email address.' }); if (!consentGranted) return res.status(400).json({ error: 'Confirm that this trusted person knows and agrees to be listed.' }); const { data, error } = await getAdmin()!.from('trusted_contacts').insert({ user_id: user.id, name: name.slice(0, 120), email: email.slice(0, 320), consent_granted: true, enabled: true }).select('id,name,email,enabled,consent_granted,created_at').single(); if (error) throw error; res.status(201).json(data) }))
app.delete('/api/trusted-contacts/:id', asyncRoute(async (req, res) => { const user = await requireUser(req); const { error } = await getAdmin()!.from('trusted_contacts').update({ enabled: false, consent_granted: false, updated_at: new Date().toISOString() }).eq('id', req.params.id).eq('user_id', user.id); if (error) throw error; res.json({ ok: true }) }))
app.post('/api/incidents/:id/trusted-notify', asyncRoute(async (req, res) => { const user = await requireUser(req); const { data: incident, error } = await getAdmin()!.from('incidents').select('id,severity,summary').eq('id', req.params.id).eq('user_id', user.id).single(); if (error || !incident) return res.status(404).json({ error: 'Incident not found.' }); const contactId = typeof req.body?.contactId === 'string' ? req.body.contactId : undefined; const notifications = await queueTrustedNotifications(getAdmin(), user.id, incident, contactId); if (contactId && !notifications.length) return res.status(404).json({ error: 'Trusted contact not found or not active.' }); res.json({ notifications }) }))
app.post('/api/incidents/:id/share', asyncRoute(async (req, res) => { const user = await requireUser(req); const { data: incident } = await getAdmin()!.from('incidents').select('id').eq('id', req.params.id).eq('user_id', user.id).single(); if (!incident) return res.status(404).json({ error: 'Incident not found.' }); res.status(201).json(await createScopedShare(getAdmin(), user.id, incident.id)) }))
app.get('/api/shared/:token', asyncRoute(async (req, res) => { const token = typeof req.params.token === 'string' ? req.params.token : ''; const client = getAdmin()!; const { data: link, error: linkError } = await client.from('shared_incident_links').select('incident_id,expires_at,revoked_at').eq('token_hash', hashShareToken(token)).single(); if (linkError || !link || link.revoked_at || new Date(link.expires_at).getTime() <= Date.now()) return res.status(404).json({ error: 'This shared incident link has expired or been revoked.' }); const { data, error } = await client.from('incidents').select('id,created_at,source_type,category,severity,risk_score,summary,explanation,ai_provider,metadata,analysis_results(*),evidence(*)').eq('id', link.incident_id).single(); if (error || !data) return res.status(404).json({ error: 'Shared incident not found.' }); const evidence = (data.evidence || [])[0]; let signedUrl: string | undefined; if (evidence?.storage_path) signedUrl = (await client.storage.from('sentinel-evidence').createSignedUrl(evidence.storage_path, 300)).data?.signedUrl; res.json({ ...data, expires_at: link.expires_at, evidence: evidence ? { ...evidence, signed_url: signedUrl } : null }) }))

app.use((error: any, req: Request, res: Response, _next: NextFunction) => { const status = Number(error?.status) || 500; console.error(JSON.stringify({ requestId: req.headers['x-request-id'] || crypto.randomUUID(), path: req.path, status, error: error?.message })); res.status(status).json({ error: status === 500 ? 'Something went wrong while processing that request.' : error.message }) })
export default app
app.delete('/api/shared/:token', asyncRoute(async (req, res) => { const user = await requireUser(req); const token = typeof req.params.token === 'string' ? req.params.token : ''; const { error } = await getAdmin()!.from('shared_incident_links').update({ revoked_at: new Date().toISOString() }).eq('token_hash', hashShareToken(token)).eq('user_id', user.id); if (error) throw error; res.json({ ok: true }) }))
